import cPickle as pickle
LetterDict = {'a\r': [int(x) for x in list('{0:012b}'.format(1))]}
LetterDict['b\r'] = [int(x) for x in list('{0:012b}'.format(2))]
LetterDict['c\r'] = [int(x) for x in list('{0:012b}'.format(3))]
LetterDict['d\r'] = [int(x) for x in list('{0:012b}'.format(4))]
LetterDict['e\r'] = [int(x) for x in list('{0:012b}'.format(5))]
LetterDict['f\r'] = [int(x) for x in list('{0:012b}'.format(6))]
LetterDict['g\r'] = [int(x) for x in list('{0:012b}'.format(7))]
LetterDict['h\r'] = [int(x) for x in list('{0:012b}'.format(8))]
LetterDict['i\r'] = [int(x) for x in list('{0:012b}'.format(9))]
LetterDict['j\r'] = [int(x) for x in list('{0:012b}'.format(10))]
LetterDict['k\r'] = [int(x) for x in list('{0:012b}'.format(11))]
LetterDict['l\r'] = [int(x) for x in list('{0:012b}'.format(12))]
LetterDict['m\r'] = [int(x) for x in list('{0:012b}'.format(13))]
LetterDict['n\r'] = [int(x) for x in list('{0:012b}'.format(14))]
LetterDict['o\r'] = [int(x) for x in list('{0:012b}'.format(15))]
LetterDict['p\r'] = [int(x) for x in list('{0:012b}'.format(16))]
LetterDict['q\r'] = [int(x) for x in list('{0:012b}'.format(17))]
LetterDict['r\r'] = [int(x) for x in list('{0:012b}'.format(18))]
LetterDict['s\r'] = [int(x) for x in list('{0:012b}'.format(19))]
LetterDict['t\r'] = [int(x) for x in list('{0:012b}'.format(20))]
LetterDict['u\r'] = [int(x) for x in list('{0:012b}'.format(21))]
LetterDict['v\r'] = [int(x) for x in list('{0:012b}'.format(22))]
LetterDict['w\r'] = [int(x) for x in list('{0:012b}'.format(23))]
LetterDict['x\r'] = [int(x) for x in list('{0:012b}'.format(24))]
LetterDict['y\r'] = [int(x) for x in list('{0:012b}'.format(25))]
LetterDict['z\r'] = [int(x) for x in list('{0:012b}'.format(26))]
pickle.dump( LetterDict, open("letterdict.p", "wb"))
